### ISSUE TITLE
Commande d'exécution rapide

### ISSUE THREAD

**Issue by Thomick** [gmattis/SimpleOCaml#42]
Lors de l'exécution d'un morceau de code, le curseur va directement à la fin de celui-ci. Il faudrait qu'il aille plutôt au début du prochain. 

En bonus : une commande **Tout exécuter**

**Comment by gmattis** [comment]
Je suis penché dessus en ce moment. Le problème est que le symbole # peut très bien venir du code de l'utilisateur qui serait exécuter et qui renverrais ça, ce que provoquerait l'exécution de la commande suivante.
Je pencherais plutôt sur un moyen de savoir quand OCaml a fini d'exécuter le code, mais je ne trouve pour l'instant pas de vraie solution :
- J'avais pensé observer en permanence le pourcentage de CPU utilisé pour savoir si OCaml exécute du code ou non, mais il arrive qu'il soit à 0% d'utilisation alors que le code n'est pas fini, et qu'il reprenne après
- J'ai aussi pensé à d'abord compiler le code puis le faire exécuter par ocamlrun qui se quitterait une fois le code terminé, mais la sortie est assez succinte, il n'y par exemple pas de retour pour "let a = 1 in a;;" ce qui est problématique.

De l'aide serait appréciée pour le coup ^^

**Comment by gmattis** [comment]
Buffer implémenté, faudra voir à l'utilisation si il y a pas de bugs.

**Comment by Thomick** [comment]
Pas de problème jusque là. Super!
