### ISSUE TITLE
Add some features

### ISSUE THREAD

**Issue by CelesteBlue-dev** [gmattis/SimpleOCaml#52]
- command line params
- drag and drop
- .ml association in settings
- automatic update

**Comment by gmattis** [comment]
Thank you for your feedback! Drag and drop and command line params will be implemented soon, but .ml association and automatic updates might a bit more complex.

**Comment by gmattis** [comment]
Command line params, drag&drop and updates were implemented. I won't implement a file association with SimpleOCaml, but it does now support "Open With" option on files.
