### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Sulray** [gmattis/SimpleOCaml#54]

**Comment by Sulray** [comment]
• You could let the user decide what colors he wants
•  It could be useful to be able to personalize the window positions and also the number of opened windows at the time
• A kind of "rainbow theme" would be appreciated, it would be a funny feature

**Comment by gmattis** [comment]
Thank you for your feedback! I thought about letting the user choose the colors for the theme, but some other issues were more important, but I'll probably try to implement it soon.
I don't think I understand what do you mean by being "able to personalize the window positions and also the number of opened windows at the time". Do you mean being able to drag and drop tabs to order them?
Raimbow theme might come one day ( ͡° ͜ʖ ͡°)
(Salut Cédric, ça va ?)

**Comment by Sulray** [comment]
I was thinking about the possibility to have like two programmation windows at the same time but yeah being able to move the tabs would be also a great improvement.
I hope so !  
You mistook me for somebody else i guess      ( ಥ  ⌣  ಥ )
