### ISSUE TITLE
Performance drop on very large files

### ISSUE THREAD

**Issue by gmattis** [gmattis/SimpleOCaml#55]
It is nearly impossible to edit very large files (10k+ lines), might be invistigated, even if nobody uses 10k+ lines code files.

**Comment by CelesteBlue-dev** [comment]
https://github.com/gmattis/SimpleOCaml/blob/ec42fff70517877e1bd07e18af8ef9fb08e57f44/simpleOcaml/OCaml.vb#L76

maybe

**Comment by gmattis** [comment]
OCaml.vb file is related to the OCaml process, so it probably doesn't come from there. I think it's probably related to the unoptimized text style updates.

**Comment by gmattis** [comment]
A partial fix was implemented, maybe I'll make some better optimizations one day.
