### ISSUE TITLE
Graphics.draw_string draw chines characters

### ISSUE THREAD

**Issue by Butanium** [gmattis/SimpleOCaml#56]
Hey the Graphics.draw_string command is buggy, it writes chinese character when I ask for "abcdefg...". At least draw_char works fine. I tested draw_string on "betterocaml.ml" and it worked.
I tested it on 2 computer so I'm pretty sure it doesn't come from my pc.
the command :
![image](https://user-images.githubusercontent.com/55806347/107010897-38775780-6797-11eb-93f1-9d4bea26d9e1.png)
the output on the graph : 
![image](https://user-images.githubusercontent.com/55806347/107010926-4200bf80-6797-11eb-8810-e39ad1187815.png)

**Comment by gmattis** [comment]
It seems that the Graphics library included in the v.1.2.2 was not working properly.
Anyway, I pushed a new release with an updated version of OCaml, and it seems to work properly now.
Can you confirm that it is now working properly for you?

**Comment by Butanium** [comment]
Hey I can't load the graphic library anymore x). But now I can finally change the theme colors, thing which didn't work for me in the previous version.
Here is the error message : 
![image](https://user-images.githubusercontent.com/55806347/107057044-4cd94580-67d3-11eb-8fba-4e4acc07b378.png)

**Comment by Butanium** [comment]
Salut bon quelques mois après j'ai trouvé comment fix le problème : il suffit de copier les .dll dans ``.\ocamlms64\lib```
[EN] To fix the problem I jut had to copy the .dll file to the path above.

**Comment by Butanium** [comment]
![image](https://user-images.githubusercontent.com/55806347/113857257-95e15200-97a2-11eb-8d93-43f3782a5247.png)
Just to signal : the draw_string method doesn't draw chinese char anymore !
