### ISSUE TITLE
Issue about 1.2.3 update (Graphics)

### ISSUE THREAD

**Issue by Sulray** [gmattis/SimpleOCaml#59]
[
![criinge](https://user-images.githubusercontent.com/42110051/110632707-3cd4cd00-81a8-11eb-813e-7e8dc9bb6651.JPG)
](url)

Graphics library seems to be in trouble with 1.2.3 update.

**Comment by Butanium** [comment]
I found a fix : you just have to copy all the dll files in ``ocamlms64\lib\ocaml\stublibs`` to ``ocamlms64\lib``
